import{a as S,S as x,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function m(o,r){const{data:s}=await S("https://pixabay.com/api/",{params:{key:"50835877-ebd7ce95b33653090cfe69fe8",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}});return s}const M=new x(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".js-load-more");function g(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:i,comments:q,downloads:v})=>`
        <li class="gallery-item">
        <a href="${a}">
        <img src="${s}" alt="${e}" class="image">
        </a>
        <div class="statist">
        <p class="text">Likes<span class="span">${t}</span></p>
        <p class="text">Views<span class="span">${i}</span></p>
        <p class="text">Comments<span class="span">${q}</span></p>
        <p class="text">Downloads<span class="span">${v}</span></p>
        </div>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function R(){f.innerHTML=""}function L(){h.style.display="block"}function d(){h.style.display="none"}function b(){y.classList.remove("load-more-hidden")}function w(){y.classList.add("load-more-hidden")}const p=document.querySelector(".form"),$=document.querySelector(".js-load-more");let n=1,c=null;d();let u=0;p.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(c=r,n=1,w(),r!==""){R(),L();try{const s=await m(c,n),a=s.hits;if(u=Math.ceil(s.totalHits/15),a.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}else g(a),n>=u?l.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight",color:"blue"}):b();p.reset()}catch{l.error({message:"Request error!",position:"topRight"})}finally{d()}}});$.addEventListener("click",async()=>{n+=1,L(),w();try{const o=await m(c,n);g(o.hits),n>=u?l.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight",color:"blue"}):b()}catch{l.error({message:"Request error!",position:"topRight"})}finally{d();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
