import{a as q,S as v,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function u(o,t){const{data:s}=await q("https://pixabay.com/api/",{params:{key:"50835877-ebd7ce95b33653090cfe69fe8",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return s}const S=new v(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".js-load-more");function y(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:b,downloads:w})=>`
        <li class="gallery-item">
        <a href="${a}">
        <img src="${s}" alt="${e}" class="image">
        </a>
        <div class="statist">
        <p class="text">Likes<span class="span">${r}</span></p>
        <p class="text">Views<span class="span">${n}</span></p>
        <p class="text">Comments<span class="span">${b}</span></p>
        <p class="text">Downloads<span class="span">${w}</span></p>
        </div>
        </li>
    `).join("");p.insertAdjacentHTML("beforeend",t),S.refresh()}function x(){p.innerHTML=""}function h(){m.style.display="block"}function d(){m.style.display="none"}function g(){f.classList.remove("load-more-hidden")}function M(){f.classList.add("load-more-hidden")}const l=document.querySelector(".form"),$=document.querySelector(".js-load-more");let i=1,L=null;d();l.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(L=t,t!==""){x(),h();try{const a=(await u(t,i)).hits;a.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(a),g())}catch{c.error({message:"Request error!",position:"topRight"})}finally{d(),l.reset()}}});$.addEventListener("click",async()=>{h(),i+=1;try{const o=await u(L,i),t=Math.ceil(o.totalHits/15);if(i>t){c.warning({message:"We are sorry, but you have reached the end of search results.",position:"topRight",color:"blue"}),M();return}y(o.hits),g()}catch{c.error({message:"Request error!",position:"topRight"})}finally{d(),l.reset();const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
